spring:
  application:
    name: api-templating
  flyway:
    enabled: true
    group: true
logging:
  level:
    org.docx4j: ERROR
    com.openhtmltopdf: ERROR
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

openapi:
  name: api-service-templating
  title: Templating
  version: '@project.version@'

springdoc:
  swagger-ui:
    operationsSorter: method

rendering:
  direct-output-as-base64: true

